name: Deploy to GitHub Pages

on:
  push:
    branches: 'main'

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm install
      - name: Read fake cname into variable
        uses: guibranco/github-file-reader-action-v2@latest
        id: fake_cname
        with:
          path: "static/FAKE_CNAME"
      - name: build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
          PUBLIC_FAKE_CNAME: '${{ steps.fake_cname.outputs.contents }}'
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # this should match the `pages` option in your adapter-static options
          path: 'build/'
  deploy:
    needs: build_site
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
